# Пользователи
## Создать нового пользователя
POST http://localhost:4000/users/register HTTP/1.1
Content-Type: application/json

{
  "email": "torans@overlook.net",
  "avatarUrl": "torrance.png",
  "name": "Jack",
  "isPro": true,
  "password": "shining"
}

###

## Авторизовать пользователя
POST http://localhost:4000/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "torans@overlook.net",
  "password": "shining"
}

###

## Проверка авторизации пользователя
GET http://localhost:4000/users/login HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRvcmFuc0BvdmVybG9vay5uZXQiLCJuYW1lIjoiSmFjayIsImlkIjoiNjY1YjY4ZmMxYWMxMWExNDQ0YTIzZWExIiwiaWF0IjoxNzE4NzA4MjA3LCJleHAiOjE3MTg4ODEwMDd9.6hMMSJ3UFBGgLsboE0ul_ZLSlBB4yXMqouLeej6FySI

###

## Завершить сеанс работы пользователя
DELETE http://localhost:4000/users/logout HTTP/1.1
Content-Type: application/json

###

## Отправить изображение
POST http://localhost:4000/users/665b68fc1ac11a1444a23ea1/avatar HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="03.jpg"
Content-Type: image/jpeg

< C:\Users\user\Desktop/03.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

## Получить список избранных предложений
GET http://localhost:4000/users/favorite HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRvcmFuc0BvdmVybG9vay5uZXQiLCJuYW1lIjoiSmFjayIsImlkIjoiNjY1YjY4ZmMxYWMxMWExNDQ0YTIzZWExIiwiaWF0IjoxNzE5MTcxNTg2LCJleHAiOjE3MTkzNDQzODZ9.FyGltnKVvY-B6TydaCaFzQeTGmvfj0tayT9sAz133n0

###

## Добавить предложения в избранное
POST http://localhost:4000/users/favorite/664f755f8da9c6dfc2b01d3e HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRvcmFuc0BvdmVybG9vay5uZXQiLCJuYW1lIjoiSmFjayIsImlkIjoiNjY1YjY4ZmMxYWMxMWExNDQ0YTIzZWExIiwiaWF0IjoxNzE5MTcxNTg2LCJleHAiOjE3MTkzNDQzODZ9.FyGltnKVvY-B6TydaCaFzQeTGmvfj0tayT9sAz133n0

###

## Удалить предложения из избранного
DELETE  http://localhost:4000/users/favorite/664f755f8da9c6dfc2b01d3e HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRvcmFuc0BvdmVybG9vay5uZXQiLCJuYW1lIjoiSmFjayIsImlkIjoiNjY1YjY4ZmMxYWMxMWExNDQ0YTIzZWExIiwiaWF0IjoxNzE5MTcxNTg2LCJleHAiOjE3MTkzNDQzODZ9.FyGltnKVvY-B6TydaCaFzQeTGmvfj0tayT9sAz133n0

###
